### ISSUE TITLE
Typst 0.13.1 and Cetz 0.3.3 issue with filled circle.

### ISSUE THREAD

**Issue by flavio20002** [cetz-package/cetz#835]
The issue is present only in the web app that uses the last Typst version. In my local environment with Typst  0.13.0 the issue in not present. The issue was introduced with cetz 0.3.3 and was not present in cetz 0.3.2.

    #import "@preview/cetz:0.3.3"
    
    #cetz.canvas({
      import cetz.draw: *
      circle((0,0), radius: 1, stroke: black, fill: black)
    })
    

![Image](https://github.com/user-attachments/assets/04bd685e-bd4c-4161-9d8c-533a36f6bbdb)

Here is a link with the Minimal, Reproducible Example

https://typst.app/project/r36QSqPkb4IpPpT4eGMZQe

In changelog of typst 0.13.1:

Visualization
Fixed [curves](https://typst.app/docs/reference/visualize/curve/) with multiple non-closed components

**Comment by johannes-wolf** [comment]
Fixed with 0.3.4.

**Comment by flavio20002** [comment]
I only looked at open issues. It would be better in my opinion to close the
issues only when the package is released in the repository. At the moment a
normale user still have the issue because he should not be able to use the
last version with a local package. Thanks a lot.

Il lun 10 mar 2025, 09:38 Johannes Wolf ***@***.***> ha
scritto:
